import type {
  DashboardStats,
  Assessment,
  Asset,
  Vulnerability,
  Finding,
  Investigation,
  Notification,
  VulnTrendPoint,
  ActivityItem,
  Resource,
  ApiKey,
  User,
  Report,
} from '../types'

// Generate 30 days of trend data
function generateTrendData(): VulnTrendPoint[] {
  const data: VulnTrendPoint[] = []
  const now = new Date()
  for (let i = 29; i >= 0; i--) {
    const date = new Date(now)
    date.setDate(date.getDate() - i)
    data.push({
      date: date.toISOString().split('T')[0],
      critical: Math.floor(Math.random() * 5) + 2,
      high: Math.floor(Math.random() * 12) + 8,
      medium: Math.floor(Math.random() * 20) + 15,
      low: Math.floor(Math.random() * 15) + 10,
      info: Math.floor(Math.random() * 25) + 20,
    })
  }
  return data
}

const recentActivity: ActivityItem[] = [
  {
    id: 'act-1',
    type: 'scan_completed',
    title: 'Port scan completed',
    description: 'Nmap scan of example.com finished - 23 open ports found',
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'act-2',
    type: 'finding_new',
    title: 'Critical finding discovered',
    description: 'CVE-2024-21762 - FortiOS SSL VPN RCE on vpn.acme.corp',
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    severity: 'CRITICAL',
  },
  {
    id: 'act-3',
    type: 'asset_discovered',
    title: 'New subdomain found',
    description: 'staging-api.acme.corp discovered via certificate transparency',
    timestamp: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
  },
  {
    id: 'act-4',
    type: 'scan_started',
    title: 'Cloud scan started',
    description: 'S3 bucket enumeration for acme.corp initiated',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'act-5',
    type: 'finding_confirmed',
    title: 'Finding confirmed',
    description: 'SQL injection on login.acme.corp confirmed by analyst',
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    severity: 'HIGH',
  },
  {
    id: 'act-6',
    type: 'scan_completed',
    title: 'SSL/TLS scan completed',
    description: 'TLS analysis of 47 domains completed - 3 certificates expiring soon',
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: 'act-7',
    type: 'finding_new',
    title: 'Exposed API key found',
    description: 'GitHub repository contains hardcoded AWS credentials',
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    severity: 'HIGH',
  },
  {
    id: 'act-8',
    type: 'asset_discovered',
    title: 'New IP range detected',
    description: '203.0.113.0/24 associated with target ASN via BGP data',
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
]

export const demoFindings: Finding[] = [
  {
    id: 'f-001',
    assessment_id: 'a-001',
    asset_id: 'asset-001',
    asset_value: 'vpn.acme.corp',
    title: 'FortiOS SSL VPN Pre-Auth RCE (CVE-2024-21762)',
    description: 'FortiOS SSL VPN is vulnerable to an out-of-bounds write vulnerability that allows a remote unauthenticated attacker to execute arbitrary code via specially crafted HTTP requests.',
    severity: 'CRITICAL',
    category: 'Remote Code Execution',
    source: 'nuclei',
    template_id: 'CVE-2024-21762',
    cve_id: 'CVE-2024-21762',
    cvss_score: 9.8,
    evidence: 'HTTP/1.1 200 OK\nServer: FortiOS/7.2.3\nFortiGate detected with vulnerable version',
    remediation: 'Upgrade FortiOS to version 7.4.3 or later. Apply vendor patch immediately.',
    status: 'open',
    found_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    confirmed_at: null,
    url: 'https://vpn.acme.corp:10443/remote/logincheck',
    matched_at: 'body',
    matcher_name: 'version-check',
    curl_command: 'curl -k https://vpn.acme.corp:10443/remote/logincheck',
    reference: ['https://nvd.nist.gov/vuln/detail/CVE-2024-21762'],
  },
  {
    id: 'f-002',
    assessment_id: 'a-001',
    asset_id: 'asset-002',
    asset_value: 'login.acme.corp',
    title: 'SQL Injection in Authentication Endpoint',
    description: 'The login form is vulnerable to SQL injection via the username parameter, allowing authentication bypass and data extraction.',
    severity: 'CRITICAL',
    category: 'Injection',
    source: 'sqlmap',
    template_id: 'sqli-auth-bypass',
    cve_id: null,
    cvss_score: 9.1,
    evidence: "Parameter: username (POST)\nType: boolean-based blind\nPayload: admin' OR '1'='1",
    remediation: 'Use parameterized queries / prepared statements. Implement input validation and WAF rules.',
    status: 'confirmed',
    found_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    confirmed_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    url: 'https://login.acme.corp/api/auth',
    matched_at: 'parameter',
    matcher_name: 'sqli-detection',
    curl_command: "curl -X POST https://login.acme.corp/api/auth -d \"username=admin'OR'1'='1&password=test\"",
    reference: ['https://owasp.org/www-community/attacks/SQL_Injection'],
  },
  {
    id: 'f-003',
    assessment_id: 'a-001',
    asset_id: 'asset-003',
    asset_value: 'api.acme.corp',
    title: 'Exposed GraphQL Introspection',
    description: 'GraphQL introspection is enabled in production, exposing the complete API schema including internal queries and mutations.',
    severity: 'HIGH',
    category: 'Information Disclosure',
    source: 'nuclei',
    template_id: 'graphql-introspection',
    cve_id: null,
    cvss_score: 7.5,
    evidence: 'Introspection query returned full schema with 47 types, 23 queries, 15 mutations',
    remediation: 'Disable GraphQL introspection in production environments.',
    status: 'open',
    found_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    confirmed_at: null,
    url: 'https://api.acme.corp/graphql',
    matched_at: 'body',
    matcher_name: 'introspection-enabled',
    curl_command: 'curl -X POST https://api.acme.corp/graphql -H "Content-Type: application/json" -d \'{"query":"{__schema{types{name}}}"}\'',
    reference: ['https://graphql.org/learn/introspection/'],
  },
  {
    id: 'f-004',
    assessment_id: 'a-001',
    asset_id: 'asset-004',
    asset_value: 'cdn.acme.corp',
    title: 'Misconfigured S3 Bucket - Public Read Access',
    description: 'S3 bucket backing cdn.acme.corp allows unauthenticated listing and read access to all objects.',
    severity: 'HIGH',
    category: 'Cloud Misconfiguration',
    source: 'cloud-scan',
    template_id: 's3-public-read',
    cve_id: null,
    cvss_score: 7.2,
    evidence: 'AWS S3 bucket acme-corp-cdn-prod allows public ListBucket and GetObject',
    remediation: 'Remove public access from the S3 bucket policy. Enable S3 Block Public Access.',
    status: 'open',
    found_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    confirmed_at: null,
    url: 'https://acme-corp-cdn-prod.s3.amazonaws.com/',
    matched_at: 'header',
    matcher_name: 'public-bucket',
    curl_command: 'curl https://acme-corp-cdn-prod.s3.amazonaws.com/',
    reference: ['https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html'],
  },
  {
    id: 'f-005',
    assessment_id: 'a-001',
    asset_id: 'asset-005',
    asset_value: 'mail.acme.corp',
    title: 'TLS 1.0 Enabled on Mail Server',
    description: 'The mail server supports TLS 1.0 which is deprecated and vulnerable to BEAST and POODLE attacks.',
    severity: 'MEDIUM',
    category: 'Cryptographic Issues',
    source: 'testssl',
    template_id: 'tls-1.0-enabled',
    cve_id: null,
    cvss_score: 5.3,
    evidence: 'TLSv1.0 supported: YES (VULNERABLE)\nProtocols: TLSv1.0 TLSv1.1 TLSv1.2',
    remediation: 'Disable TLS 1.0 and TLS 1.1. Only allow TLS 1.2 and TLS 1.3.',
    status: 'open',
    found_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    confirmed_at: null,
    url: null,
    matched_at: 'protocol',
    matcher_name: 'tls-version',
    curl_command: 'nmap --script ssl-enum-ciphers -p 443 mail.acme.corp',
    reference: ['https://datatracker.ietf.org/doc/rfc8996/'],
  },
  {
    id: 'f-006',
    assessment_id: 'a-001',
    asset_id: 'asset-006',
    asset_value: 'staging.acme.corp',
    title: 'Exposed .env File',
    description: 'Environment configuration file accessible at /.env containing database credentials and API keys.',
    severity: 'HIGH',
    category: 'Information Disclosure',
    source: 'dirsearch',
    template_id: 'exposed-env-file',
    cve_id: null,
    cvss_score: 7.5,
    evidence: 'DB_HOST=rds-prod.abc123.us-east-1.rds.amazonaws.com\nDB_PASSWORD=P@ssw0rd_pr0d\nAWS_SECRET_KEY=...',
    remediation: 'Remove .env from web root. Add .env to .htaccess deny rules. Rotate all exposed credentials immediately.',
    status: 'open',
    found_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    confirmed_at: null,
    url: 'https://staging.acme.corp/.env',
    matched_at: 'body',
    matcher_name: 'env-file',
    curl_command: 'curl -s https://staging.acme.corp/.env',
    reference: ['https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/05-Enumerate_Infrastructure_and_Application_Admin_Interfaces'],
  },
  {
    id: 'f-007',
    assessment_id: 'a-001',
    asset_id: 'asset-007',
    asset_value: 'blog.acme.corp',
    title: 'WordPress xmlrpc.php Enabled',
    description: 'XML-RPC interface is enabled, allowing brute-force attacks and DDoS amplification.',
    severity: 'MEDIUM',
    category: 'Misconfiguration',
    source: 'nuclei',
    template_id: 'wordpress-xmlrpc',
    cve_id: null,
    cvss_score: 5.0,
    evidence: 'xmlrpc.php returns 200 OK with valid XML-RPC response',
    remediation: 'Disable XML-RPC if not needed. Use .htaccess to block access to xmlrpc.php.',
    status: 'open',
    found_at: new Date(Date.now() - 1000 * 60 * 400).toISOString(),
    confirmed_at: null,
    url: 'https://blog.acme.corp/xmlrpc.php',
    matched_at: 'body',
    matcher_name: 'xmlrpc-enabled',
    curl_command: 'curl -s https://blog.acme.corp/xmlrpc.php',
    reference: ['https://blog.sucuri.net/2015/10/brute-force-amplification-attacks-against-wordpress-xmlrpc.html'],
  },
  {
    id: 'f-008',
    assessment_id: 'a-001',
    asset_id: 'asset-008',
    asset_value: 'acme.corp',
    title: 'Missing DMARC Record',
    description: 'No DMARC DNS record found. Domain is susceptible to email spoofing attacks.',
    severity: 'LOW',
    category: 'Email Security',
    source: 'dns-recon',
    template_id: 'missing-dmarc',
    cve_id: null,
    cvss_score: 3.7,
    evidence: 'dig TXT _dmarc.acme.corp - No records found',
    remediation: 'Add a DMARC DNS TXT record: _dmarc.acme.corp IN TXT "v=DMARC1; p=quarantine; rua=mailto:dmarc@acme.corp"',
    status: 'open',
    found_at: new Date(Date.now() - 1000 * 60 * 500).toISOString(),
    confirmed_at: null,
    url: null,
    matched_at: 'dns',
    matcher_name: 'dmarc-missing',
    curl_command: 'dig TXT _dmarc.acme.corp',
    reference: ['https://dmarc.org/overview/'],
  },
  {
    id: 'f-009',
    assessment_id: 'a-001',
    asset_id: 'asset-009',
    asset_value: 'admin.acme.corp',
    title: 'Admin Panel Accessible Without MFA',
    description: 'Administrative interface accessible without multi-factor authentication requirement.',
    severity: 'MEDIUM',
    category: 'Authentication',
    source: 'manual',
    template_id: 'admin-no-mfa',
    cve_id: null,
    cvss_score: 6.5,
    evidence: 'Admin panel at /admin accepts single-factor authentication',
    remediation: 'Enforce MFA for all administrative access. Consider IP whitelisting.',
    status: 'open',
    found_at: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    confirmed_at: null,
    url: 'https://admin.acme.corp/admin',
    matched_at: 'page',
    matcher_name: 'admin-access',
    curl_command: null,
    reference: ['https://cheatsheetseries.owasp.org/cheatsheets/Multifactor_Authentication_Cheat_Sheet.html'],
  },
  {
    id: 'f-010',
    assessment_id: 'a-001',
    asset_id: 'asset-010',
    asset_value: 'docs.acme.corp',
    title: 'Server Version Disclosure',
    description: 'HTTP response headers reveal server software and version information.',
    severity: 'INFO',
    category: 'Information Disclosure',
    source: 'nuclei',
    template_id: 'server-version-disclosure',
    cve_id: null,
    cvss_score: 0.0,
    evidence: 'Server: nginx/1.18.0 (Ubuntu)\nX-Powered-By: Express 4.17.1',
    remediation: 'Remove or obfuscate Server and X-Powered-By headers.',
    status: 'open',
    found_at: new Date(Date.now() - 1000 * 60 * 700).toISOString(),
    confirmed_at: null,
    url: 'https://docs.acme.corp',
    matched_at: 'header',
    matcher_name: 'server-header',
    curl_command: 'curl -I https://docs.acme.corp',
    reference: ['https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/01-Information_Gathering/02-Fingerprint_Web_Server'],
  },
]

export const demoAssets: Asset[] = [
  {
    id: 'asset-001',
    assessment_id: 'a-001',
    value: 'vpn.acme.corp',
    type: 'subdomain',
    status: 'live',
    first_seen: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    last_seen: new Date().toISOString(),
    technologies: [
      { id: 't1', name: 'FortiOS', version: '7.2.3', category: 'VPN', confidence: 95 },
      { id: 't2', name: 'FortiGate', version: '', category: 'Firewall', confidence: 90 },
    ],
    ports: [
      { id: 'p1', asset_id: 'asset-001', port_number: 443, protocol: 'tcp', state: 'open', service: 'https', version: 'FortiOS', banner: '', product: 'FortiGate' },
      { id: 'p2', asset_id: 'asset-001', port_number: 10443, protocol: 'tcp', state: 'open', service: 'https', version: 'FortiOS SSL VPN', banner: '', product: 'FortiGate' },
    ],
    dns_records: [
      { id: 'd1', asset_id: 'asset-001', record_type: 'A', name: 'vpn.acme.corp', value: '203.0.113.10', ttl: 3600 },
    ],
    tls_certificate: {
      id: 'tls1',
      asset_id: 'asset-001',
      subject: 'vpn.acme.corp',
      issuer: "Let's Encrypt Authority X3",
      serial_number: 'AB:CD:EF:12:34',
      not_before: '2024-01-15T00:00:00Z',
      not_after: '2024-10-15T00:00:00Z',
      days_until_expiry: 45,
      key_algorithm: 'RSA',
      key_size: 2048,
      signature_algorithm: 'SHA256withRSA',
      san: ['vpn.acme.corp'],
      is_expired: false,
      is_self_signed: false,
      grade: 'B',
      issues: ['TLS 1.0 enabled', 'Weak cipher suites detected'],
    },
    findings_count: 1,
    risk_score: 9.8,
    metadata: {},
  },
  {
    id: 'asset-002',
    assessment_id: 'a-001',
    value: 'login.acme.corp',
    type: 'subdomain',
    status: 'live',
    first_seen: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
    last_seen: new Date().toISOString(),
    technologies: [
      { id: 't3', name: 'React', version: '18.2.0', category: 'JavaScript Framework', confidence: 100 },
      { id: 't4', name: 'nginx', version: '1.24.0', category: 'Web Server', confidence: 95 },
      { id: 't5', name: 'Node.js', version: '', category: 'Runtime', confidence: 80 },
    ],
    ports: [
      { id: 'p3', asset_id: 'asset-002', port_number: 443, protocol: 'tcp', state: 'open', service: 'https', version: 'nginx 1.24.0', banner: '', product: 'nginx' },
      { id: 'p4', asset_id: 'asset-002', port_number: 80, protocol: 'tcp', state: 'open', service: 'http', version: 'nginx 1.24.0', banner: '', product: 'nginx' },
    ],
    dns_records: [
      { id: 'd2', asset_id: 'asset-002', record_type: 'A', name: 'login.acme.corp', value: '203.0.113.20', ttl: 3600 },
      { id: 'd3', asset_id: 'asset-002', record_type: 'CNAME', name: 'login.acme.corp', value: 'lb-prod-1.acme.corp', ttl: 300 },
    ],
    tls_certificate: null,
    findings_count: 1,
    risk_score: 9.1,
    metadata: {},
  },
  {
    id: 'asset-003',
    assessment_id: 'a-001',
    value: 'api.acme.corp',
    type: 'subdomain',
    status: 'live',
    first_seen: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    last_seen: new Date().toISOString(),
    technologies: [
      { id: 't6', name: 'GraphQL', version: '', category: 'API', confidence: 100 },
      { id: 't7', name: 'Express', version: '4.18.2', category: 'Web Framework', confidence: 90 },
      { id: 't8', name: 'Node.js', version: '20.11.0', category: 'Runtime', confidence: 85 },
    ],
    ports: [
      { id: 'p5', asset_id: 'asset-003', port_number: 443, protocol: 'tcp', state: 'open', service: 'https', version: '', banner: '', product: '' },
    ],
    dns_records: [
      { id: 'd4', asset_id: 'asset-003', record_type: 'A', name: 'api.acme.corp', value: '203.0.113.30', ttl: 300 },
    ],
    tls_certificate: null,
    findings_count: 1,
    risk_score: 7.5,
    metadata: {},
  },
  {
    id: 'asset-004',
    assessment_id: 'a-001',
    value: 'cdn.acme.corp',
    type: 'subdomain',
    status: 'live',
    first_seen: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    last_seen: new Date().toISOString(),
    technologies: [
      { id: 't9', name: 'Amazon S3', version: '', category: 'Cloud Storage', confidence: 100 },
      { id: 't10', name: 'CloudFront', version: '', category: 'CDN', confidence: 95 },
    ],
    ports: [
      { id: 'p6', asset_id: 'asset-004', port_number: 443, protocol: 'tcp', state: 'open', service: 'https', version: '', banner: '', product: 'AmazonS3' },
    ],
    dns_records: [
      { id: 'd5', asset_id: 'asset-004', record_type: 'CNAME', name: 'cdn.acme.corp', value: 'd1234.cloudfront.net', ttl: 300 },
    ],
    tls_certificate: null,
    findings_count: 1,
    risk_score: 7.2,
    metadata: {},
  },
  {
    id: 'asset-005',
    assessment_id: 'a-001',
    value: 'mail.acme.corp',
    type: 'subdomain',
    status: 'live',
    first_seen: new Date(Date.now() - 1000 * 60 * 60 * 24 * 120).toISOString(),
    last_seen: new Date().toISOString(),
    technologies: [
      { id: 't11', name: 'Exchange', version: '2019', category: 'Mail Server', confidence: 85 },
    ],
    ports: [
      { id: 'p7', asset_id: 'asset-005', port_number: 25, protocol: 'tcp', state: 'open', service: 'smtp', version: 'Microsoft ESMTP', banner: '', product: 'Exchange' },
      { id: 'p8', asset_id: 'asset-005', port_number: 443, protocol: 'tcp', state: 'open', service: 'https', version: '', banner: '', product: 'Exchange OWA' },
      { id: 'p9', asset_id: 'asset-005', port_number: 993, protocol: 'tcp', state: 'open', service: 'imaps', version: '', banner: '', product: '' },
    ],
    dns_records: [
      { id: 'd6', asset_id: 'asset-005', record_type: 'A', name: 'mail.acme.corp', value: '203.0.113.40', ttl: 3600 },
      { id: 'd7', asset_id: 'asset-005', record_type: 'MX', name: 'acme.corp', value: 'mail.acme.corp', ttl: 3600, priority: 10 },
    ],
    tls_certificate: null,
    findings_count: 1,
    risk_score: 5.3,
    metadata: {},
  },
  {
    id: 'asset-006',
    assessment_id: 'a-001',
    value: 'staging.acme.corp',
    type: 'subdomain',
    status: 'live',
    first_seen: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    last_seen: new Date().toISOString(),
    technologies: [
      { id: 't12', name: 'Django', version: '4.2', category: 'Web Framework', confidence: 90 },
      { id: 't13', name: 'Python', version: '3.11', category: 'Language', confidence: 85 },
      { id: 't14', name: 'PostgreSQL', version: '', category: 'Database', confidence: 70 },
    ],
    ports: [
      { id: 'p10', asset_id: 'asset-006', port_number: 443, protocol: 'tcp', state: 'open', service: 'https', version: '', banner: '', product: '' },
      { id: 'p11', asset_id: 'asset-006', port_number: 8080, protocol: 'tcp', state: 'open', service: 'http-proxy', version: '', banner: '', product: '' },
    ],
    dns_records: [
      { id: 'd8', asset_id: 'asset-006', record_type: 'A', name: 'staging.acme.corp', value: '203.0.113.50', ttl: 300 },
    ],
    tls_certificate: null,
    findings_count: 1,
    risk_score: 7.5,
    metadata: {},
  },
  {
    id: 'asset-007',
    assessment_id: 'a-001',
    value: 'blog.acme.corp',
    type: 'subdomain',
    status: 'live',
    first_seen: new Date(Date.now() - 1000 * 60 * 60 * 24 * 180).toISOString(),
    last_seen: new Date().toISOString(),
    technologies: [
      { id: 't15', name: 'WordPress', version: '6.4.2', category: 'CMS', confidence: 100 },
      { id: 't16', name: 'PHP', version: '8.2', category: 'Language', confidence: 90 },
      { id: 't17', name: 'Apache', version: '2.4.58', category: 'Web Server', confidence: 95 },
    ],
    ports: [
      { id: 'p12', asset_id: 'asset-007', port_number: 443, protocol: 'tcp', state: 'open', service: 'https', version: 'Apache/2.4.58', banner: '', product: 'Apache' },
    ],
    dns_records: [],
    tls_certificate: null,
    findings_count: 1,
    risk_score: 5.0,
    metadata: {},
  },
  {
    id: 'asset-008',
    assessment_id: 'a-001',
    value: 'acme.corp',
    type: 'domain',
    status: 'live',
    first_seen: new Date(Date.now() - 1000 * 60 * 60 * 24 * 365).toISOString(),
    last_seen: new Date().toISOString(),
    technologies: [
      { id: 't18', name: 'Cloudflare', version: '', category: 'CDN/WAF', confidence: 100 },
      { id: 't19', name: 'Next.js', version: '14', category: 'Framework', confidence: 85 },
    ],
    ports: [
      { id: 'p13', asset_id: 'asset-008', port_number: 443, protocol: 'tcp', state: 'open', service: 'https', version: 'cloudflare', banner: '', product: 'Cloudflare' },
      { id: 'p14', asset_id: 'asset-008', port_number: 80, protocol: 'tcp', state: 'open', service: 'http', version: '', banner: '', product: '' },
    ],
    dns_records: [
      { id: 'd9', asset_id: 'asset-008', record_type: 'A', name: 'acme.corp', value: '104.18.1.100', ttl: 300 },
      { id: 'd10', asset_id: 'asset-008', record_type: 'NS', name: 'acme.corp', value: 'ns1.cloudflare.com', ttl: 86400 },
      { id: 'd11', asset_id: 'asset-008', record_type: 'TXT', name: 'acme.corp', value: 'v=spf1 include:_spf.google.com ~all', ttl: 3600 },
    ],
    tls_certificate: null,
    findings_count: 1,
    risk_score: 3.7,
    metadata: {},
  },
  {
    id: 'asset-009',
    assessment_id: 'a-001',
    value: 'admin.acme.corp',
    type: 'subdomain',
    status: 'live',
    first_seen: new Date(Date.now() - 1000 * 60 * 60 * 24 * 200).toISOString(),
    last_seen: new Date().toISOString(),
    technologies: [
      { id: 't20', name: 'React', version: '18', category: 'JavaScript Framework', confidence: 90 },
      { id: 't21', name: 'Material UI', version: '5', category: 'UI Library', confidence: 85 },
    ],
    ports: [
      { id: 'p15', asset_id: 'asset-009', port_number: 443, protocol: 'tcp', state: 'open', service: 'https', version: '', banner: '', product: '' },
    ],
    dns_records: [],
    tls_certificate: null,
    findings_count: 1,
    risk_score: 6.5,
    metadata: {},
  },
  {
    id: 'asset-010',
    assessment_id: 'a-001',
    value: 'docs.acme.corp',
    type: 'subdomain',
    status: 'live',
    first_seen: new Date(Date.now() - 1000 * 60 * 60 * 24 * 150).toISOString(),
    last_seen: new Date().toISOString(),
    technologies: [
      { id: 't22', name: 'nginx', version: '1.18.0', category: 'Web Server', confidence: 100 },
      { id: 't23', name: 'Express', version: '4.17.1', category: 'Web Framework', confidence: 90 },
    ],
    ports: [
      { id: 'p16', asset_id: 'asset-010', port_number: 443, protocol: 'tcp', state: 'open', service: 'https', version: 'nginx/1.18.0', banner: '', product: 'nginx' },
    ],
    dns_records: [],
    tls_certificate: null,
    findings_count: 1,
    risk_score: 1.0,
    metadata: {},
  },
  {
    id: 'asset-011',
    assessment_id: 'a-001',
    value: 'jenkins.acme.corp',
    type: 'subdomain',
    status: 'live',
    first_seen: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    last_seen: new Date().toISOString(),
    technologies: [
      { id: 't24', name: 'Jenkins', version: '2.426.1', category: 'CI/CD', confidence: 100 },
      { id: 't25', name: 'Java', version: '17', category: 'Runtime', confidence: 90 },
    ],
    ports: [
      { id: 'p17', asset_id: 'asset-011', port_number: 8080, protocol: 'tcp', state: 'open', service: 'http', version: 'Jetty 10.0.18', banner: '', product: 'Jenkins' },
    ],
    dns_records: [],
    tls_certificate: null,
    findings_count: 0,
    risk_score: 4.0,
    metadata: {},
  },
  {
    id: 'asset-012',
    assessment_id: 'a-001',
    value: '203.0.113.0/24',
    type: 'cidr',
    status: 'live',
    first_seen: new Date(Date.now() - 1000 * 60 * 60 * 24 * 365).toISOString(),
    last_seen: new Date().toISOString(),
    technologies: [],
    ports: [],
    dns_records: [],
    tls_certificate: null,
    findings_count: 0,
    risk_score: 0,
    metadata: { hosts_up: 47, hosts_total: 254 },
  },
  {
    id: 'asset-013',
    assessment_id: 'a-002',
    value: 'app.targetcorp.io',
    type: 'subdomain',
    status: 'live',
    first_seen: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    last_seen: new Date().toISOString(),
    technologies: [
      { id: 't26', name: 'Vue.js', version: '3.4', category: 'JavaScript Framework', confidence: 95 },
      { id: 't27', name: 'FastAPI', version: '', category: 'Web Framework', confidence: 80 },
    ],
    ports: [
      { id: 'p18', asset_id: 'asset-013', port_number: 443, protocol: 'tcp', state: 'open', service: 'https', version: '', banner: '', product: '' },
    ],
    dns_records: [],
    tls_certificate: null,
    findings_count: 3,
    risk_score: 6.8,
    metadata: {},
  },
  {
    id: 'asset-014',
    assessment_id: 'a-002',
    value: 'api.targetcorp.io',
    type: 'subdomain',
    status: 'live',
    first_seen: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    last_seen: new Date().toISOString(),
    technologies: [
      { id: 't28', name: 'FastAPI', version: '0.109', category: 'Web Framework', confidence: 95 },
      { id: 't29', name: 'uvicorn', version: '', category: 'ASGI Server', confidence: 85 },
    ],
    ports: [
      { id: 'p19', asset_id: 'asset-014', port_number: 443, protocol: 'tcp', state: 'open', service: 'https', version: '', banner: '', product: '' },
      { id: 'p20', asset_id: 'asset-014', port_number: 8000, protocol: 'tcp', state: 'open', service: 'http', version: 'uvicorn', banner: '', product: 'FastAPI' },
    ],
    dns_records: [],
    tls_certificate: null,
    findings_count: 2,
    risk_score: 5.5,
    metadata: {},
  },
  {
    id: 'asset-015',
    assessment_id: 'a-003',
    value: '10.0.0.0/16',
    type: 'cidr',
    status: 'live',
    first_seen: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    last_seen: new Date().toISOString(),
    technologies: [],
    ports: [],
    dns_records: [],
    tls_certificate: null,
    findings_count: 5,
    risk_score: 4.2,
    metadata: { hosts_up: 312, hosts_total: 65534 },
  },
]

export const demoAssessments: Assessment[] = [
  {
    id: 'a-001',
    name: 'Acme Corp Full Assessment',
    target: 'acme.corp',
    target_type: 'domain',
    status: 'completed',
    scan_mode: 'aggressive',
    phases: ['enumeration', 'dns', 'osint', 'port_scan', 'ssl', 'cloud', 'crawler', 'web', 'api', 'vuln', 'cve'],
    flags: {
      passive_only: false,
      stealth: false,
      screenshots: true,
      cve: true,
      crawl: true,
      agent: false,
      no_osint: false,
      diff: false,
      baseline: false,
    },
    risk_score: 8.4,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    completed_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    created_by: 'admin',
    findings_count: 47,
    assets_count: 12,
    organization_id: 'org-001',
  },
  {
    id: 'a-002',
    name: 'TargetCorp Bug Bounty Recon',
    target: 'targetcorp.io',
    target_type: 'domain',
    status: 'running',
    scan_mode: 'medium',
    phases: ['enumeration', 'dns', 'port_scan', 'ssl', 'web'],
    flags: {
      passive_only: false,
      stealth: true,
      screenshots: true,
      cve: false,
      crawl: true,
      agent: false,
      no_osint: true,
      diff: true,
      baseline: false,
    },
    risk_score: 5.2,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    completed_at: null,
    created_by: 'admin',
    findings_count: 12,
    assets_count: 8,
    organization_id: 'org-001',
  },
  {
    id: 'a-003',
    name: 'Internal Network Audit',
    target: '10.0.0.0/16',
    target_type: 'cidr',
    status: 'pending',
    scan_mode: 'light',
    phases: ['port_scan', 'vuln'],
    flags: {
      passive_only: false,
      stealth: false,
      screenshots: false,
      cve: true,
      crawl: false,
      agent: false,
      no_osint: true,
      diff: false,
      baseline: false,
    },
    risk_score: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    completed_at: null,
    created_by: 'admin',
    findings_count: 0,
    assets_count: 1,
    organization_id: 'org-001',
  },
]

export const demoVulnerabilities: Vulnerability[] = [
  {
    id: 'v-001',
    cve_id: 'CVE-2024-21762',
    title: 'FortiOS Out-of-Bounds Write',
    description: 'A out-of-bounds write vulnerability in FortiOS SSL VPN may allow a remote unauthenticated attacker to execute arbitrary code or command via specially crafted HTTP requests.',
    severity: 'CRITICAL',
    cvss_score: 9.8,
    cvss_vector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    epss_score: 0.97,
    epss_percentile: 99.8,
    is_kev: true,
    kev_date_added: '2024-02-09',
    affected_assets: ['vpn.acme.corp'],
    affected_assets_count: 1,
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-21762', 'https://www.fortiguard.com/psirt/FG-IR-24-015'],
    published_date: '2024-02-09',
    modified_date: '2024-03-01',
    cwe_id: 'CWE-787',
    cwe_name: 'Out-of-bounds Write',
    remediation: 'Upgrade to FortiOS 7.4.3 or later.',
    exploit_available: true,
  },
  {
    id: 'v-002',
    cve_id: 'CVE-2023-44487',
    title: 'HTTP/2 Rapid Reset Attack',
    description: 'The HTTP/2 protocol allows a denial of service (server resource consumption) because request cancellation can reset many streams quickly.',
    severity: 'HIGH',
    cvss_score: 7.5,
    cvss_vector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H',
    epss_score: 0.82,
    epss_percentile: 97.5,
    is_kev: true,
    kev_date_added: '2023-10-10',
    affected_assets: ['api.acme.corp', 'login.acme.corp', 'docs.acme.corp'],
    affected_assets_count: 3,
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2023-44487'],
    published_date: '2023-10-10',
    modified_date: '2024-01-15',
    cwe_id: 'CWE-400',
    cwe_name: 'Uncontrolled Resource Consumption',
    remediation: 'Update HTTP/2 implementations. Apply vendor patches for nginx, Apache, and Node.js.',
    exploit_available: true,
  },
  {
    id: 'v-003',
    cve_id: 'CVE-2024-3400',
    title: 'PAN-OS Command Injection',
    description: 'A command injection vulnerability in the GlobalProtect feature of Palo Alto Networks PAN-OS software.',
    severity: 'CRITICAL',
    cvss_score: 10.0,
    cvss_vector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H',
    epss_score: 0.95,
    epss_percentile: 99.5,
    is_kev: true,
    kev_date_added: '2024-04-12',
    affected_assets: [],
    affected_assets_count: 0,
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-3400'],
    published_date: '2024-04-12',
    modified_date: '2024-04-20',
    cwe_id: 'CWE-77',
    cwe_name: 'Command Injection',
    remediation: 'Apply PAN-OS hotfix. Enable Threat Prevention signatures.',
    exploit_available: true,
  },
  {
    id: 'v-004',
    cve_id: 'CVE-2024-1709',
    title: 'ConnectWise ScreenConnect Auth Bypass',
    description: 'Authentication bypass vulnerability in ConnectWise ScreenConnect allowing direct access to the setup wizard.',
    severity: 'CRITICAL',
    cvss_score: 10.0,
    cvss_vector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H',
    epss_score: 0.93,
    epss_percentile: 99.2,
    is_kev: true,
    kev_date_added: '2024-02-22',
    affected_assets: [],
    affected_assets_count: 0,
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-1709'],
    published_date: '2024-02-19',
    modified_date: '2024-03-15',
    cwe_id: 'CWE-288',
    cwe_name: 'Authentication Bypass Using an Alternate Path',
    remediation: 'Update ScreenConnect to version 23.9.8 or later.',
    exploit_available: true,
  },
  {
    id: 'v-005',
    cve_id: 'CVE-2023-46805',
    title: 'Ivanti Connect Secure Auth Bypass',
    description: 'An authentication bypass vulnerability in Ivanti Connect Secure and Ivanti Policy Secure allows remote attackers to access restricted resources.',
    severity: 'HIGH',
    cvss_score: 8.2,
    cvss_vector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:N',
    epss_score: 0.89,
    epss_percentile: 98.5,
    is_kev: true,
    kev_date_added: '2024-01-10',
    affected_assets: [],
    affected_assets_count: 0,
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2023-46805'],
    published_date: '2024-01-10',
    modified_date: '2024-02-01',
    cwe_id: 'CWE-287',
    cwe_name: 'Improper Authentication',
    remediation: 'Apply Ivanti security update. Reset credentials.',
    exploit_available: true,
  },
]

export const demoInvestigations: Investigation[] = [
  {
    id: 'inv-001',
    title: 'FortiOS VPN Exploitation Assessment',
    description: 'Investigating the critical FortiOS SSL VPN vulnerability on vpn.acme.corp. Determining if exploitation has occurred and assessing blast radius.',
    status: 'in_progress',
    priority: 'critical',
    findings: ['f-001'],
    findings_count: 1,
    notes: [
      {
        id: 'n-001',
        content: 'FortiOS 7.2.3 confirmed vulnerable. Checking for IOCs in VPN logs.',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
        created_by: 'admin',
      },
      {
        id: 'n-002',
        content: 'No evidence of exploitation found in available logs. Recommending immediate patch.',
        created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        created_by: 'admin',
      },
    ],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    created_by: 'admin',
    assignee: 'admin',
    tags: ['vpn', 'rce', 'fortinet', 'critical'],
    mitre_techniques: ['T1190', 'T1133'],
  },
  {
    id: 'inv-002',
    title: 'Exposed Credentials in .env File',
    description: 'Investigating the exposed .env file on staging.acme.corp containing database credentials and AWS keys.',
    status: 'open',
    priority: 'high',
    findings: ['f-006'],
    findings_count: 1,
    notes: [],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    created_by: 'admin',
    assignee: null,
    tags: ['credentials', 'exposure', 'aws', 'database'],
    mitre_techniques: ['T1552.001', 'T1078'],
  },
  {
    id: 'inv-003',
    title: 'SQL Injection in Login Portal',
    description: 'SQL injection vulnerability in login.acme.corp authentication endpoint. Assessing data exposure risk.',
    status: 'in_progress',
    priority: 'critical',
    findings: ['f-002'],
    findings_count: 1,
    notes: [
      {
        id: 'n-003',
        content: 'Confirmed boolean-based blind SQLi. Backend appears to be PostgreSQL.',
        created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
        created_by: 'admin',
      },
    ],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    created_by: 'admin',
    assignee: 'admin',
    tags: ['sqli', 'authentication', 'data-breach'],
    mitre_techniques: ['T1190', 'T1078'],
  },
]

export const demoNotifications: Notification[] = [
  {
    id: 'notif-001',
    title: 'Critical vulnerability found',
    message: 'CVE-2024-21762 (CVSS 9.8) detected on vpn.acme.corp. Immediate action required.',
    type: 'error',
    severity: 'CRITICAL',
    is_read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    link: '/findings',
    source: 'nuclei',
  },
  {
    id: 'notif-002',
    title: 'Scan completed',
    message: 'Acme Corp Full Assessment completed. 47 findings across 12 assets.',
    type: 'success',
    severity: 'INFO',
    is_read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    link: '/assessments',
    source: 'system',
  },
  {
    id: 'notif-003',
    title: 'New asset discovered',
    message: 'staging-api.acme.corp found via certificate transparency logs.',
    type: 'info',
    severity: 'MEDIUM',
    is_read: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    link: '/assets',
    source: 'enumeration',
  },
  {
    id: 'notif-004',
    title: 'Certificate expiring soon',
    message: 'TLS certificate for vpn.acme.corp expires in 45 days.',
    type: 'warning',
    severity: 'MEDIUM',
    is_read: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    link: '/assets/asset-001',
    source: 'ssl-check',
  },
  {
    id: 'notif-005',
    title: 'Exposed credentials detected',
    message: '.env file with database credentials found on staging.acme.corp.',
    type: 'error',
    severity: 'HIGH',
    is_read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    link: '/findings',
    source: 'dirsearch',
  },
  {
    id: 'notif-006',
    title: 'Scheduled scan started',
    message: 'TargetCorp Bug Bounty Recon scan started (medium mode, stealth enabled).',
    type: 'info',
    severity: 'INFO',
    is_read: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    link: '/assessments',
    source: 'scheduler',
  },
]

export const demoReports: Report[] = [
  {
    id: 'r-001',
    assessment_id: 'a-001',
    title: 'Acme Corp Full Assessment Report',
    format: 'html',
    status: 'ready',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    file_size: 2457600,
    download_url: '/api/v1/reports/r-001/download',
  },
  {
    id: 'r-002',
    assessment_id: 'a-001',
    title: 'Acme Corp SARIF Export',
    format: 'sarif',
    status: 'ready',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    file_size: 524288,
    download_url: '/api/v1/reports/r-002/download',
  },
]

export const demoApiKeys: ApiKey[] = [
  { id: 'key-001', name: 'Shodan API', key_preview: 'aBc...XyZ', service: 'shodan', is_valid: true, created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(), last_used: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString() },
  { id: 'key-002', name: 'VirusTotal', key_preview: 'def...789', service: 'virustotal', is_valid: true, created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(), last_used: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString() },
  { id: 'key-003', name: 'Censys API', key_preview: 'ghi...012', service: 'censys', is_valid: false, created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(), last_used: null },
  { id: 'key-004', name: 'Anthropic (Agent)', key_preview: 'sk-...abc', service: 'anthropic', is_valid: true, created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(), last_used: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString() },
  { id: 'key-005', name: 'Slack Webhook', key_preview: 'https://hooks...', service: 'slack', is_valid: true, created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(), last_used: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString() },
]

export const demoUsers: User[] = [
  {
    id: 'user-001',
    username: 'admin',
    email: 'admin@exposurescopex.local',
    full_name: 'System Administrator',
    role: 'admin',
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 365).toISOString(),
    last_login: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'user-002',
    username: 'analyst',
    email: 'analyst@exposurescopex.local',
    full_name: 'Security Analyst',
    role: 'analyst',
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 180).toISOString(),
    last_login: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 'user-003',
    username: 'viewer',
    email: 'viewer@exposurescopex.local',
    full_name: 'Report Viewer',
    role: 'viewer',
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    last_login: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
]

export const demoResources: Resource[] = [
  // Search & Discovery
  { id: 'res-001', name: 'Shodan', description: 'Search engine for Internet-connected devices. Find exposed services, open ports, and vulnerable systems worldwide.', url: 'https://shodan.io', category: 'Search & Discovery', subcategory: 'IoT Search', tags: ['search', 'iot', 'ports', 'services'], is_favorite: true, integration_status: 'integrated' },
  { id: 'res-002', name: 'Censys', description: 'Internet-wide scanning platform. Discover certificates, hosts, and services across IPv4 space.', url: 'https://search.censys.io', category: 'Search & Discovery', subcategory: 'Internet Scanning', tags: ['search', 'certificates', 'hosts'], is_favorite: false, integration_status: 'integrated' },
  { id: 'res-003', name: 'Fofa', description: 'Cyberspace search engine from China. Extensive coverage of Asian internet infrastructure.', url: 'https://fofa.info', category: 'Search & Discovery', subcategory: 'Internet Scanning', tags: ['search', 'china', 'infrastructure'], is_favorite: false, integration_status: 'external' },
  { id: 'res-004', name: 'ZoomEye', description: 'Cyberspace search engine. Search by component, port, service, or keyword.', url: 'https://www.zoomeye.org', category: 'Search & Discovery', subcategory: 'Internet Scanning', tags: ['search', 'components', 'services'], is_favorite: false, integration_status: 'external' },
  { id: 'res-005', name: 'GreyNoise', description: 'Understand internet noise. Distinguish targeted attacks from mass scanning.', url: 'https://www.greynoise.io', category: 'Search & Discovery', subcategory: 'Threat Intelligence', tags: ['noise', 'scanning', 'threats'], is_favorite: false, integration_status: 'external' },
  // DNS Intelligence
  { id: 'res-006', name: 'crt.sh', description: 'Certificate Transparency log search. Discover subdomains via SSL certificate records.', url: 'https://crt.sh', category: 'DNS Intelligence', subcategory: 'CT Logs', tags: ['dns', 'certificates', 'subdomains'], is_favorite: true, integration_status: 'integrated' },
  { id: 'res-007', name: 'DNSDumpster', description: 'Domain research tool for finding host information. Free DNS recon and research.', url: 'https://dnsdumpster.com', category: 'DNS Intelligence', subcategory: 'DNS Recon', tags: ['dns', 'domains', 'mapping'], is_favorite: false, integration_status: 'external' },
  { id: 'res-008', name: 'ViewDNS', description: 'Collection of free DNS and network tools. Reverse IP, port scan, DNSSEC, and more.', url: 'https://viewdns.info', category: 'DNS Intelligence', subcategory: 'DNS Tools', tags: ['dns', 'reverse-ip', 'whois'], is_favorite: false, integration_status: 'external' },
  { id: 'res-009', name: 'SecurityTrails', description: 'Total internet inventory. Historical DNS data, WHOIS, and associated domains.', url: 'https://securitytrails.com', category: 'DNS Intelligence', subcategory: 'DNS History', tags: ['dns', 'historical', 'whois'], is_favorite: false, integration_status: 'available' },
  // Threat Intelligence
  { id: 'res-010', name: 'VirusTotal', description: 'Analyze suspicious files, URLs, domains, and IPs. Aggregate threat intelligence from 70+ vendors.', url: 'https://www.virustotal.com', category: 'Threat Intelligence', subcategory: 'Multi-Scanner', tags: ['malware', 'urls', 'files', 'analysis'], is_favorite: true, integration_status: 'integrated' },
  { id: 'res-011', name: 'AbuseIPDB', description: 'IP address abuse reporting and checking database. Community-driven threat intelligence.', url: 'https://www.abuseipdb.com', category: 'Threat Intelligence', subcategory: 'IP Reputation', tags: ['ip', 'abuse', 'reputation'], is_favorite: false, integration_status: 'external' },
  { id: 'res-012', name: 'AlienVault OTX', description: 'Open Threat Exchange. Community-driven threat intelligence platform with IOC sharing.', url: 'https://otx.alienvault.com', category: 'Threat Intelligence', subcategory: 'IOC Sharing', tags: ['ioc', 'threat-intel', 'community'], is_favorite: false, integration_status: 'external' },
]

export const demoDashboardStats: DashboardStats = {
  total_assets: 127,
  total_domains: 15,
  total_vulnerabilities: 89,
  critical_findings: 8,
  high_findings: 23,
  medium_findings: 31,
  low_findings: 18,
  info_findings: 9,
  risk_score: 7.2,
  active_scans: 2,
  completed_scans: 14,
  assets_change_percent: 12,
  vulns_change_percent: -5,
  severity_breakdown: [
    { name: 'Critical', value: 8, color: '#ef4444' },
    { name: 'High', value: 23, color: '#f97316' },
    { name: 'Medium', value: 31, color: '#eab308' },
    { name: 'Low', value: 18, color: '#3b82f6' },
    { name: 'Info', value: 9, color: '#64748b' },
  ],
  vuln_trend: generateTrendData(),
  recent_findings: demoFindings.slice(0, 10),
  recent_activity: recentActivity,
  top_risks: demoFindings.filter((f) => f.severity === 'CRITICAL' || f.severity === 'HIGH').slice(0, 5),
}
