"use client";

import { useEffect, useState } from "react";
import { API, apiFetch } from "../../../lib/api";

type Report = { id:string; scan_id:string; status:string; assessment_name:string; target:string; scan_status:string; generated_at:string; manifest:{ finding_count?:number; observation_count?:number; artifact_count?:number; execution_status?:string; outputs?:Record<string,unknown>; report_error?:string } };

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([]);
  const [error, setError] = useState("");
  const [regenerating, setRegenerating] = useState<string | null>(null);
  async function refresh() { const response = await apiFetch("/api/v3/reports", { cache:"no-store" }); if (!response.ok) throw new Error("Report inventory is unavailable"); setReports(await response.json()); setError(""); }
  async function regenerate(scanId:string) { setRegenerating(scanId); setError(""); try { const response = await apiFetch(`/api/v3/reports/${scanId}/regenerate`, { method:"POST" }); if (!response.ok) { const payload = await response.json().catch(() => null) as { detail?:string } | null; throw new Error(payload?.detail ?? `Report regeneration failed (${response.status})`); } await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Report regeneration failed"); } finally { setRegenerating(null); } }
  useEffect(() => { refresh().catch((reason:Error) => setError(reason.message)); }, []);
  return <main className="workspacePage"><header className="pageHeader"><div><p className="kicker">CLIENT DELIVERABLES</p><h1>Reports</h1><p>Versioned terminal-run reports backed by the immutable evidence manifest, including complete, partial, failed, blocked, and cancelled outcomes.</p></div><button className="secondaryAction" onClick={() => refresh()}>REFRESH</button></header>{error && <p className="formError">{error}</p>}<section className="reportLedger"><div className="reportHead"><span>ASSESSMENT</span><span>STATUS</span><span>COVERAGE</span><span>GENERATED</span><span>DOWNLOADS</span></div>{reports.length === 0 ? <div className="emptyState"><strong>No reports generated yet</strong><span>Every terminal assessment run will appear here, including partial, failed, blocked, and cancelled coverage.</span></div> : reports.map((report) => <article className="reportRow" key={report.id}><div><strong>{report.assessment_name}</strong><small>{report.target}</small></div><span className={`statusLabel status-${report.scan_status}`}><i />{report.status}</span><span>{(report.manifest.execution_status ?? report.scan_status).toUpperCase()} execution · {report.manifest.finding_count ?? 0} findings · {report.manifest.observation_count ?? 0} observations · {report.manifest.artifact_count ?? 0} artifacts</span><time>{new Date(report.generated_at).toLocaleString()}</time><div className="reportDownloads">{(["docx","pdf","evidence"] as const).map((format) => <a key={format} className={report.manifest.outputs?.[format] ? "" : "downloadUnavailable"} href={report.manifest.outputs?.[format] ? `${API}/api/v3/reports/${report.scan_id}/download/${format}` : undefined}>{format === "evidence" ? "ZIP" : format.toUpperCase()}</a>)}<button className="reportRegenerate" disabled={regenerating === report.scan_id} onClick={() => regenerate(report.scan_id)}>{regenerating === report.scan_id ? "BUILDING" : "REGENERATE"}</button></div>{report.manifest.report_error && <p className="reportError">{report.manifest.report_error}</p>}</article>)}</section></main>;
}
